### ISSUE TITLE
How would one change the times it takes until the user gets banned

### ISSUE THREAD

**Issue by IeuanGol** [msciotti/MannersBotJS#1]
I want two warnings then they get banned.

**Comment by msciotti** [comment]
Hey there! Hm, it's a bit of an old project, but if you're interested in using it I could certainly extend that functionality without much issue. What I'll do is make a constant for the number of warnings allowed before banning, and then that constant could be changed.

**Comment by msciotti** [comment]
You can now change the `MAX_WARNINGS` constant in the `punishment.js` file to configure the max number of warnings.
